
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Provider from '@/components/Provider';




export const metadata = {
  title: 'Likesgiving',
  description: 'Generated by create next app',

}



export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

      <body className={inter.className}>


        <Provider>
          {children}
        </Provider>


      </body>
    </html>
  )
}
