"use client";


import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
const inter = Inter({ subsets: ['latin'] })
import {ReduxProvider} from '../redux/ReduxProvider'
import { useSelector } from 'react-redux'
import { redirect } from 'next/navigation';

export const metadata = {
  title: 'MyApp',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  const isAuth = useSelector((state) => state.auth.isAuth); 
  if (!isAuth) 
    return redirect('/login')
  return (
    <html lang="en">

      <body className={inter.className}>
      
      <ReduxProvider>
        {children}
      </ReduxProvider>
      
      </body>
    </html>
  )
}
